name: Deploy to S3

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # S3 버킷이 위치한 리전

      - name: Sync files to S3
        run: |
          aws s3 sync ./dist s3://zogakzip.mju.4 --delete